# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :cluster4 do |node|
    node.vm.box = "chef/centos-6.6"
    node.vm.network :private_network, ip: '10.10.20.18'
    node.vm.network :private_network, ip: '10.11.20.18', netmask: '255.0.0.0', virtualbox__intnet: "private_couchbase"
    node.vm.hostname = "cluster4"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.customize ["modifyvm", :id, "--natnet1", "10.0.3.0/24"]
      vb.customize ["modifyvm", :id, "--macaddress1", "080027B4224C"]
    end

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::hosts"
      chef.add_recipe "setup::couchbase"
      chef.add_recipe "setup::couchbase4-initialize"

      chef.json = {
        :setup => {
          :namespace => "couchbase4.vb.ns.com",
          :os_name   => "CentOS 6.6 x86",
        },
        :hosts => [
          { :ip => '10.11.20.18', :fqdn => 'cluster4', :aliases => ['cluster4.vb.ns.com'] },
        ],

        :couchbase => {
          :path => 'http://packages.couchbase.com/releases/4.0.0/',
          :package => 'couchbase-server-community-4.0.0-centos6.x86_64',
          :first => 'cluster4.vb.ns.com',
        }
      }
    end
  end

end
