# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :cluster do |node|
    node.vm.box = "chef/centos-6.6"
    node.vm.network :private_network, ip: '10.10.20.16'
    node.vm.network :private_network, ip: '10.11.20.16', netmask: '255.0.0.0', virtualbox__intnet: "private_couchbase"
    node.vm.hostname = "cluster"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natnet1", "10.0.3.0/24"]
      vb.customize ["modifyvm", :id, "--macaddress1", "080027B4224C"]
    end

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::hosts"
      chef.add_recipe "setup::java"
      chef.add_recipe "setup::couchbase"
      chef.add_recipe "setup::couchbase-initialize"

      chef.json = {
        :setup => {
          :namespace => "couchbase.vb.ns.com",
          :os_name   => "CentOS 6.6 x86",
        },
        :hosts => [
          { :ip => '10.11.20.16', :fqdn => 'cluster', :aliases => ['cluster.vb.ns.com'] },
          { :ip => '10.11.21.16', :fqdn => 'node001', :aliases => ['node001.vb.ns.com'] },
          { :ip => '10.10.22.16', :fqdn => 'xdcr', :aliases => ['xdcr.vb.ns.com'] },
        ],
        :couchbase => {
          :first => 'cluster.vb.ns.com',
        }
      }
    end
  end

  config.vm.define :node001 do |node|
    node.vm.box = "chef/centos-6.6"
    node.vm.network :private_network, ip: '10.10.21.16'
    node.vm.network :private_network, ip: '10.11.21.16', netmask: '255.0.0.0', virtualbox__intnet: "private_couchbase"
    node.vm.hostname = "node001"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natnet1", "10.0.4.0/24"]
      vb.customize ["modifyvm", :id, "--macaddress1", "080027B4124D"]
    end

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::hosts"
      chef.add_recipe "setup::couchbase"
      chef.add_recipe "setup::couchbase-cluster"

      chef.json = {
        :setup => {
          :namespace => "couchbase001.vb.ns.com",
          :os_name   => "CentOS 6.6 x86",
        },
        :hosts => [
          { :ip => '10.11.20.16', :fqdn => 'cluster', :aliases => ['cluster.vb.ns.com'] },
          { :ip => '10.11.21.16', :fqdn => 'node001', :aliases => ['node001.vb.ns.com'] },
          { :ip => '10.10.22.16', :fqdn => 'xdcr', :aliases => ['xdcr.vb.ns.com'] },
        ],
        :couchbase => {
          :first => 'cluster.vb.ns.com',
          :node => 'node001.vb.ns.com',
        }
      }
    end
  end

  config.vm.define :xdcr do |node|
    node.vm.box = "chef/centos-6.6"
    node.vm.network :private_network, ip: '10.10.22.16'
    node.vm.network :private_network, ip: '10.12.22.16', netmask: '255.0.0.0', virtualbox__intnet: "private_couchbase"
    node.vm.hostname = "xdcr"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natnet1", "10.0.5.0/24"]
      vb.customize ["modifyvm", :id, "--macaddress1", "080027B4224E"]
    end

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::hosts"
      chef.add_recipe "setup::couchbase"
      chef.add_recipe "setup::couchbase-initialize"

      chef.json = {
        :setup => {
          :namespace => "couchbase-xdcr.vb.ns.com",
          :os_name   => "CentOS 6.6 x86",
        },
        :hosts => [
          { :ip => '10.11.20.16', :fqdn => 'cluster', :aliases => ['cluster.vb.ns.com'] },
          { :ip => '10.11.21.16', :fqdn => 'node001', :aliases => ['node001.vb.ns.com'] },
          { :ip => '10.12.22.16', :fqdn => 'xdcr', :aliases => ['xdcr.vb.ns.com'] },
        ],
        :couchbase => {
          :first => 'xdcr.vb.ns.com',
        }
      }
    end
  end
end
