# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :cluster do |node|
    node.vm.box = "chef/centos-6.6"
    node.vm.network :private_network, ip: '10.10.20.16'
    node.vm.hostname = "cluster"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natnet1", "10.0.3.0/24"]
      vb.customize ["modifyvm", :id, "--macaddress1", "080027B4224C"]
    end

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::couchbase"

      chef.json = {
        :setup => {
          :namespace => "couchbase.vb.ns.com",
          :os_name   => "CentOS 6.6 x86",
        }
      }
    end
  end

  config.vm.define :node001 do |node|
    node.vm.box = "chef/centos-6.6"
    node.vm.network :private_network, ip: '10.10.21.16'
    node.vm.hostname = "node001"

    node.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.customize ["modifyvm", :id, "--natnet1", "10.0.4.0/24"]
      vb.customize ["modifyvm", :id, "--macaddress1", "080027B4124D"]
    end

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::couchbase"

      chef.json = {
        :setup => {
          :namespace => "couchbase2.vb.ns.com",
          :os_name   => "CentOS 6.6 x86",
        }
      }
    end
  end
end
