# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.6"
  config.vm.network :private_network, ip: '10.10.50.15'

  config.omnibus.chef_version = :latest
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"

    chef.add_recipe "setup"
    chef.add_recipe "setup::elasticsearch"
    chef.add_recipe "setup::fluentd-elasticsearch"
    chef.add_recipe "setup::kibana"

    chef.json = {
      :setup => {
        :namespace => "log-analysis.vb.ns.com",
        :os_name   => "CentOS 6.6 x86",
      }
    }
  end
end
