# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.network :private_network, ip: '172.16.10.16', netmask: '255.255.0.0'

  config.omnibus.chef_version = :latest
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"

    chef.add_recipe "setup"
    chef.add_recipe "setup::ruby"

    chef.json = {
        :setup => {
            :namespace => "ruby.vb.ns.com",
            :os_name   => "CentOS 6.5 x86",
        },
        :rbenv => {
            :ruby => {
                :versions => ["2.1.2", "1.9.3-p547"],
                :global   => "2.1.2",
            }
        }
    }
  end
end
