# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :agent do |node|
    node.vm.box = "chef/centos-6.5"
    node.vm.network :private_network, ip: '10.10.30.16'
    node.vm.hostname = 'agent'

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::fluentd"
      chef.add_recipe "setup::fluentd-settings"

      chef.json = {
        :setup => {
          :namespace => "fluentd.vb.ns.com",
          :os_name   => "CentOS 6.5 x86",
        },
        :fluentd => {
          :collector => {
            :address => '10.10.31.16'
          }
        }
      }
    end
  end

  config.vm.define :collector do |node|
    node.vm.box = "chef/centos-6.5"
    node.vm.network :private_network, ip: '10.10.31.16'
    node.vm.hostname = 'collector'

    node.omnibus.chef_version = :latest
    node.vm.provision "chef_solo" do |chef|
      chef.cookbooks_path = "../chef-repo/cookbooks"

      chef.add_recipe "setup"
      chef.add_recipe "setup::fluentd"
      chef.add_recipe "setup::fluentd-settings"

      chef.json = {
        :setup => {
          :namespace => "collector.vb.ns.com",
          :os_name   => "CentOS 6.5 x86",
        }
      }
    end
  end
end
