# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.network :private_network, ip: '172.16.30.11', netmask: '255.255.0.0'

  config.omnibus.chef_version = :latest
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"

    chef.add_recipe "setup"
    chef.add_recipe "setup::docker"

    chef.json = {
        :setup => {
            :namespace => "docker.vb.ns.com",
            :os_name   => "CentOS 6.5 x86",
        }
    }
  end
end
