# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.6"
  config.vm.network :private_network, ip: '10.10.10.15'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end

  config.omnibus.chef_version = :latest
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"

    chef.add_recipe "setup"
    chef.add_recipe "setup::java"
    chef.add_recipe "setup::tomcat"
    chef.add_recipe "setup::java-build"
    chef.add_recipe "setup::java-play"

    chef.json = {
      :setup => {
        :namespace => "java.vb.ns.com",
        :os_name   => "CentOS 6.6 x86",
      }
    }
  end
end
