---
- hosts: web
  sudo: yes
  tasks:
    - name: be sure httpd is installed
      yum: name=httpd state=installed

    - name: be sure httpd is running and enable
      service: name=httpd state=running enabled=yes
