# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "chef/centos-6.5"
  config.vm.network :private_network, ip: '10.10.10.20'

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end

  config.omnibus.chef_version = :latest
  config.vm.provision "chef_solo" do |chef|
    chef.cookbooks_path = "../chef-repo/cookbooks"

    chef.add_recipe "setup"
    chef.add_recipe "setup::apache"
    chef.add_recipe "setup::php-source"
    chef.add_recipe "setup::php-utils"

    chef.json = {
      :setup => {
        :namespace => "php52.vb.ns.com",
        :os_name   => "CentOS 6.5 x86",
      },
      :php => {
        :configure => {
          :apxs => "--with-apxs2=/usr/sbin/apxs",
        },
      },
    }
  end
end
